#org: evertonildo
#app: api-crediceara
service: portal-do-credito-pre-cadastro
provider:
  name: aws
  runtime: nodejs12.x
  stage: hom
  region: sa-east-1
  memorySize: 128
  iam:
    role: arn:aws:iam::527520683957:role/papelzero-qa-ZappaLambdaExecutionRole
functions:
  app:
    handler: ./server.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
          
plugins:
  - serverless-offline
